### ISSUE TITLE
Tuxindex

### ISSUE THREAD

**Issue by Owlblocks** [Tuxemon/Tuxemon#452] opened 2018-08-18 20:30 UTC
Hi everyone!

I'm new to open source coding (and for that matter, python, although I have experience with programming in Java and have been able to learn a lot through attempting to mess with the source code for Tuxemon). Because I was less familiar with the codebase, I wanted to do something for the game that was in many ways independent of the current code. Because of that, I started work on the Tuxindex. Scrolling around on the wiki, I saw some mention of a "Tuxepedia" and even a few mockup renditions of a gui, although they looked pretty barebones and more conceptual than anything else. I already have a sprite I made (and I think looks pretty good, considering I'm not much of an artist) although if there's another one that's fine.

![tuxindex](https://user-images.githubusercontent.com/26911009/44302934-244df000-a2e8-11e8-8497-4e03e0c7680f.png)

As I've started to develop this feature, I've arrived upon a few pieces of information:

1) there's a process to open source development. I never got any input on this, and while I know the "official issues" are the focus I'm not sure if my code is something the Tuxemon team would want (I hope so, haha) in the official release, or if I was supposed to go through a longer issue process.

2) it wasn't as closed off as I thought. While it's true that a lot of my code is able to go into my own classes/files, I had to make some modifications to the larger file source in order to make the tuxindex work. Things like allow items with the "Tool" type (I wasn't sure what else to call it; Consumable was the only example of a type I could find) to not have a target when using them from the ItemMenuState (it also gives that item the Control/game as the target, in order to allow general modification ie opening up menus), or adding an "open_index" method/function in the Item class. While I hope I didn't mess anything up, I'm not sure how the open-source/git process deals with changes to files. Thus, I'm not sure if my code would fit in with the larger project.

While I'm not sure if the Tuxemon team is looking at implementing my code when I'm done, it would be great if I could have input on my code/process because I'm new to open source and unsure of how to go about it. I'm pretty sure that my code will be somewhat buggy/inefficient as I'm unused to python and this project, although a lot of it I've been able to model off of code elsewhere (as of right now, the list of tuxemon in the index is just a copy of the item menu with some tweaks, and I'm learning the way menus/states are composed through that). So far I have a tuxindex item that, when used, will create a tuxindex menu with an unlocalized list of all the tuxemon in the game (although it doesn't allow for scrolling yet, so the list goes off the screen). I can open a given tuxemon entry to a blank menu, which will have the various information. I'm also wanting to have multiple tabs, to be able to look at different information like "summary", "possible techniques", "evolutions", etc.

Is there any feedback on the way I'm trying to structure the menu? Advice on how to better communicate? Any would be appreciated :)

I'm happy to help try to contribute to an actual project, and I hope to continue to work on this project, and to try to learn a thing or to while I'm at it.

**Comment by Sanglorian** [comment] 2018-08-19 09:39
Hi Owlblocks! Thanks for helping out. I'm not a programmer, but I did come up with the sample GUIs so happy to help with that angle and discuss any ideas you have!

Although there is talk of a "Tuxepedia App", I think the Tuxepedia will end up being available from the menu (like Save Game, etc) rather than tucked away under items. 

In terms of displaying monsters, I'd like to see them displayed in ID order in three different styles:

1. Red text for monsters that have not been encountered before. These cannot be selected - there is no further information on them than their name. 
2. Blue text for monsters that have been encountered, but not caught. These can be selected and show some information (Type, picture - or at least a silhouette, etc)
3. Face sprite animation and blue text for monsters that have been caught. These can be selected and show full information (blurb, technique set, etc)

I like your idea of multiple tabs for extra information.

**Comment by bitcraft** [comment] 2019-01-24 17:43
Paging @Owlblocks are you still interested in working on this issue?

**Comment by Sanglorian** [comment] 2019-02-05 22:34
My mockups for the Tuxepedia are on the wiki: https://wiki.tuxemon.org/index.php?title=Tuxepedia_App

I think this would be a great part of the project to get rolling again!

**Comment by 1sra3l** [comment] 2021-11-10 17:53
@bitcraft I think this issue could be solved by moving it to a separate repo.
I can write you a program if you outline the information you need compiled and where the sources are.
I am interested in making a Tuxedex to browse the Tuxemon separate from the game.

**Comment by bitcraft** [comment] 2021-11-10 18:06
ty for your idea, but i don't agree that splitting the repo will have any difference at all.  the core of the issue is making an in-game viewer/browser of the monsters.  we don't need a viewer for the content outside of the game.  the wiki serves that role (and i do acknowledge that is is broken).  we already have a monster viewer/browser for the game.  its old, but im sure it won't take much to get it up to date https://github.com/Tuxemon/Tuxemon-MonsterMaker

**Comment by bitcraft** [comment] 2021-11-10 18:07
you are of course welcome to do what you would like with the game content, as long as you follow the licenses that the content is covered by.

**Comment by 1sra3l** [comment] 2021-11-10 18:47
ok, thanks

**Closed** 2023-06-11 07:28 UTC
Labels: Feature Request, GUI
