### ISSUE TITLE
Localized names of NPCs

### ISSUE THREAD

**Issue by Qiangong2** [Tuxemon/Tuxemon#765] opened 2020-04-24 08:10 UTC
Overall, I have tried to make the NPC names of the main characters be rather vowel heavy so they can fit with other languages reasonably well. However, it doesn't work for all. Look at Aeble, Allie, and John. John is relatively simple to translate between languages, but Aeble and Allie will need to be redesigned for different languages. I foresee this being more of an issue in the future as more and more NPCs are added.

#760 talks about this a little

This will probably not be finished until the final release.

**Comment by kerizane** [comment] 2022-09-24 17:17
Duplicate of #760

**Closed** 2023-06-11 07:50 UTC
Labels: Locale
