### ISSUE TITLE
Dialogues "outside" maps aren't cleaned

### ISSUE THREAD

**Issue by airon90** [Tuxemon/Tuxemon#469] opened 2018-10-07 16:49 UTC
Screenshots self-describe what happens.

![schermata da 2018-10-07 16-49-23](https://user-images.githubusercontent.com/139841/46584265-911c7580-ca61-11e8-92e2-2662613c32f0.png)
![schermata da 2018-10-07 18-16-12](https://user-images.githubusercontent.com/139841/46584266-91b50c00-ca61-11e8-90ec-7970e32f120a.png)

**Comment by bitcraft** [comment] 2018-10-08 13:33
This is caused by out of date libraries.  Please make sure tuxemon and all the dependencies are up to date.  `pip install -r requirements.txt` should do that.

**Comment by airon90** [comment] 2018-10-08 16:48
It is still present even after getting all dependencies updated.

**Comment by kerizane** [comment] 2018-10-29 22:36
The issue is probably with pyscroll. Does it definitely work for you bitcraft?

**Comment by bitcraft** [comment] 2018-10-30 15:14
Technically Tuxemon is trampling over the map where pyscroll manages, so Tuxemon should be cleaning up after itself.  To put it another way, pyscroll is cleaning its map each render, but is not aware that Tuxemon is drawing dialogs over the map as well.

I don't believe a fix is require for pyscroll since that would involve sharing knowledge between pyscroll/tuxemon that areas of the screen need to be cleared.  The fix should be in Tuxemon, since it is no clearing the dialogs.

There was in the past, a state that cleared the frame each frame to prevent this, but it has been broken i guess at some point.

**Comment by kerizane** [comment] 2018-10-30 18:49
Further discussion in https://github.com/Tuxemon/Tuxemon/issues/449. I got a bit confused and stopped being able to produce the big after editing the pyscroll dependency (and forgot about doing so).

**Comment by kerizane** [comment] 2018-10-31 09:52
```
            if (not state.transparent
                    and state.rect == full_screen
                    and not state.force_draw):
                break

```
(force_draw doesn't work, but that's besides the point.)

The background state doesn't get drawn, as worldstate covers the entire screen. When I set force_draw on background state, (and I fixed the implementation) I found that messed with some transitions. 

My current idea is to have WorldState.rect track its own size better: if we think pyscroll isn't managing the leftmost 2 columns, then the rect won't claim to overlap them. This would allow BackgroundState to be drawn.

**Comment by bitcraft** [comment] 2018-10-31 21:31
The changes to the state/control rendering were a bit hasty, so its possible I broke "force draw" at that point.  TBH, i'm not really committed to it, because at the time it was even a temporary solution to managing widgets and I still consider it temporary.  Getting the "dirty" portion of the screen from pyscroll is not a bad solution, and would be fine.

**Comment by kerizane** [comment] 2018-11-28 09:10
@bitcraft This is fixed.

**Closed** 2018-11-28 13:47 UTC
