### ISSUE TITLE
Flood causes freeze of the game

### ISSUE THREAD

**Issue by JaskRendix** [Tuxemon/Tuxemon#1277] opened 2022-09-03 07:48 UTC
**Describe the bug**
I was doing some testing for #1232 and I discovered the following bug. Flood (technique) causes freeze of the game. The player is forced to close the window.

**To Reproduce**
1. add one of the following monsters through add_monster (add_monster monsterslug,5)
2. monsters (bigfin, conileaf, d0llf1n, dollfin, dune_pincher, manosting, nudiflot_female, nudiflot_male, poinchin, saurchin, skwib)
3. go to battle with trainer or random_monster
4. use Flood

**Expected behavior**
Not freezing

**Desktop (please complete the following information):**
 - OS: Ubuntu 22
 - Python 3.10.4

**Comment by JaskRendix** [comment] 2022-09-03 08:12
This is the cause, flood.json

It crashes:
```
  "target": {
    "enemy monster": 0,
    "enemy team": 2,
```
It doesn't crash anymore with this:
```
  "target": {
    "enemy monster": 2,
    "enemy team": 0,
```
or:
```
  "target": {
    "enemy monster": 2,
    "enemy team": 2,
```
I'm not sure if it's correct, but since it's a damage. I have the PR ready eventually. 

Edit:
I ran a check and I think it's the cause. By the way, flood is the only technique with **"enemy team": 2**

**Comment by kerizane** [comment] 2022-09-03 08:29
Thanks, but this is a duplicate of https://github.com/Tuxemon/Tuxemon/issues/1176

**Closed as completed by kerizane** 2022-09-03 08:29 UTC
