### ISSUE TITLE
Bug: crash after losing battle (trainer or monster)

### ISSUE THREAD

**Issue by JaskRendix** [Tuxemon/Tuxemon#1270] opened 2022-08-30 13:12 UTC
**Describe the bug**
Crash after losing a battle.
My fight was a Rockitten lv5 vs Cataspike lv3. My Rockitten has Ram, Boulder and Thunderball.

**To Reproduce**
1. Go to grass or engage fight with a trainer.
2. Fight with the monster or the trainer.
3. Exactly after the last attack (NPC to your monster), the game crashes

```
/usr/lib/python3/dist-packages/apport/report.py:13: DeprecationWarning: the imp module is deprecated in favour of importlib and slated for removal in Python 3.12; see the module's documentation for alternative uses
  import fnmatch, glob, traceback, errno, sys, atexit, locale, imp, stat
Traceback (most recent call last):
  File "/home/voltaire/Tuxemon/run_tuxemon.py", line 87, in <module>
    main.main(load_slot=args.slot)
  File "/home/voltaire/Tuxemon/tuxemon/main.py", line 116, in main
    client.main()
  File "/home/voltaire/Tuxemon/tuxemon/client.py", line 315, in main
    update(clock_tick)
  File "/home/voltaire/Tuxemon/tuxemon/client.py", line 366, in update
    self.update_states(time_delta)
  File "/home/voltaire/Tuxemon/tuxemon/client.py", line 389, in update_states
    self.state_manager.update(time_delta)
  File "/home/voltaire/Tuxemon/tuxemon/state.py", line 427, in update
    state.update(time_delta)
  File "/home/voltaire/Tuxemon/tuxemon/states/combat/combat.py", line 224, in update
    super().update(time_delta)
  File "/home/voltaire/Tuxemon/tuxemon/state.py", line 219, in update
    self.animations.update(time_delta)
  File "/home/voltaire/.local/lib/python3.10/site-packages/pygame/sprite.py", line 539, in update
    sprite.update(*args, **kwargs)
  File "/home/voltaire/Tuxemon/tuxemon/animation.py", line 266, in update
    self.finish()
  File "/home/voltaire/Tuxemon/tuxemon/animation.py", line 278, in finish
    self._execute_callbacks("on interval")
  File "/home/voltaire/Tuxemon/tuxemon/animation.py", line 114, in _execute_callbacks
    [cb() for cb in callbacks]
  File "/home/voltaire/Tuxemon/tuxemon/animation.py", line 114, in <listcomp>
    [cb() for cb in callbacks]
  File "/home/voltaire/Tuxemon/tuxemon/states/combat/combat.py", line 1047, in check_party_hp
    self.faint_monster(monster)
  File "/home/voltaire/Tuxemon/tuxemon/states/combat/combat.py", line 1008, in faint_monster
    winners.give_experience(awarded_exp)
  File "/home/voltaire/Tuxemon/tuxemon/monster.py", line 434, in give_experience
    self.level_up()
  File "/home/voltaire/Tuxemon/tuxemon/monster.py", line 484, in level_up
    if move.level_learned == self.level:
AttributeError: 'dict' object has no attribute 'level_learned'
```

**Expected behavior**
Lose and then get teleported to the last center.

**Desktop (please complete the following information):**
 - OS: Ubuntu 22
 - Python 3.10.4

**Comment by kerizane** [comment] 2022-08-30 13:41
Thanks for reporting; there's already a fix ready :)

https://github.com/Tuxemon/Tuxemon/pull/1230

**Comment by kerizane** [comment] 2022-08-30 14:13
Made a more minimal fix so it can be reviewed faster.

**Comment by kerizane** [comment] 2022-08-30 14:47
I can't merge my own changes, if you raise a duplicate of https://github.com/Tuxemon/Tuxemon/pull/1271/files I will merge it.

**Comment by JaskRendix** [comment] 2022-08-30 17:40
Done

**Closed as completed** 2022-08-30 17:56 UTC
