### ISSUE TITLE
Boulder move doesn't hit

### ISSUE THREAD

**Issue by ryanhanli** [Tuxemon/Tuxemon#731] opened 2020-04-10 20:11 UTC
Boulder seems to have a 0% hit rate no matter what.  I've tested it in multiple battles and it seems to be a dead move.  Rockkitten is the specific Tuxemon using the move boulder.

**Comment by xirsoi** [comment] 2020-04-10 21:34
i can confirm, boulder is useless. it's never hit for me.

**Comment by kerizane** [comment] 2020-04-13 15:14
It's meant to heal the user. Maybe it's failing cause you're at full health?

We should improve the failure message.

**Comment by kerizane** [comment] 2020-04-13 15:18
Looks like it was never implemented properly.

**Comment by xirsoi** [comment] 2020-04-13 15:27
We need to figure out target selection then, because It's NOT clear at all that Boulder is meant to be used on yourself.

The name doesn't even make it clear, I assumed it did tons of damage by literally dropping a boulder on the target.

**Comment by kerizane** [comment] 2020-04-13 15:48
We also shouldn't be able to attack ourselves.

**Comment by Sanglorian** [comment] 2020-04-14 00:40
Boulder - like a lot of techniques - has no effect at the moment because all it does is give a condition (in this case, to the user). The idea is it builds a protective boulder around the user (happy to change its name to something clearer, of course!) 

I think the targetting system is only needed in battles where it's more than one-on-one. Currently, each technique describes how the user and how the target (i.e. opponent) are affected.

**Comment by bitcraft** [comment] 2020-04-14 15:14
Target selection works by reading this dictionary:
```
  "target": {
    "enemy monster": 2,
    "enemy team": 0,
    "enemy trainer": 0,
    "item": 0,
    "own monster": 1,
    "own team": 0,
    "own trainer": 0
  },
```
If the number is non-zero, then it is added to a list and they are sorted by the value.  So, in this case you can target all monsters (including your own), but an enemy monster will be the default target because it is the highest number.  Its been a long time since this was implemented, but that should be the way it works.

**Comment by bitcraft** [comment] 2020-04-17 20:45
To close this ticket:

- [ ] Create or verify the "Hard Shell" status effect
- [ ] Remove healing effect from the boulder json
- [ ] Apply the "Hard Shell" effect with boulder (using `category`, look at poison for reference)
- [ ] Fix the targeting to default to own monster
- [ ] Find out how damage is reduced, then make code (`def calculate_damage(...)`)
- [ ] Find out when the status effect wears off

**Comment by Sanglorian** [comment] 2020-04-18 13:46
I can clear up a couple of those:

- Damage is reduced by raising the user's Armour stat - so there's no need for additional code beyond temporarily raising the user's Armour. 
- The status effect should wear off when another one is applied, either wearing off but not having the new condition applied (for a negative condition) or wearing off and having the new condition applied (for a positive condition). 

https://wiki.tuxemon.org/index.php?title=Category:Condition

**Comment by bitcraft** [comment] 2020-04-20 19:42
related: #512. while implementing boulder/hardshell, one could consider refactoring our existing system for status effects and try to implement conditions, then roll them together.

**Comment by ryanhanli** [comment] 2020-04-20 19:51
I'll try and implement a system for this and fix the boulder move itself.

**Comment by ryanhanli** [comment] 2020-04-20 19:52
> related: #512. while implementing boulder/hardshell, one could consider refactoring our existing system for status effects and try to implement conditions, then roll them together.

I'll try and implement a system for this and fix the boulder move itself.

**Comment by bitcraft** [comment] 2020-04-20 19:52
sweet.  please keep us updated with your plans....it will make code review a lot easier! :wink:

**Comment by ryanhanli** [comment] 2020-05-08 22:35
> sweet. please keep us updated with your plans....it will make code review a lot easier! 😉

Sorry for the late response I was working on another issue, which I just put in a pull request for.  I've been tinkering around with this issue and have a few ideas on how to implement it, so I'll try them out and see if I can get it working.

**Comment by bitcraft** [comment] 2020-05-20 00:30
i would implement it by collecting all the various ways we can handle the "lifecycle".  i think it would be "until removed", "until replaced", "until expired".  poison is "until removed".  hardshell is "until replaced", i think.
then add this value to each technique json.  then in the technique.py file, you will need to implement each style.  for hardshell, you will apply it only if it is not currently on the monster.  other ones will be applied each round.   then, you need to implement something like "debuff_xxxxx" where X is the name of the technique.  then find the places where status effects are removed and replace them to a call on the Technique object called "remove_status_effect(monster, name)"  something like that
that would be enough to implement hardshell and close the ticket.

**Comment by bitcraft** [comment] 2022-04-20 03:14
partially fixed https://github.com/Tuxemon/Tuxemon/commit/8d6295981c003c5e225d6bc7bd2f77b45b5f518c

**Closed** 2023-04-11 18:04 UTC
Labels: Easy, Investigation, Combat
