### ISSUE TITLE
Game freezes after first battle

### ISSUE THREAD

**Issue by Camilotk** [Tuxemon/Tuxemon#2239] opened 2024-01-31 17:03 UTC
**Describe the bug**
The game freezes after the first encounter in Cathedral mode.

**To Reproduce**
1. Run `python3 run_tuxemon.py` on fresh cloned repo on main after install the dependencies on venv.
> The output of this command here is:
> ```
> pygame-menu 4.4.3
> Git Hash: 034f5de1
> Enabling logging of all modules.
> [2024-01-31 13:54:20,447] tuxemon.rumble - ERROR - No rumble backends available.
> ```
2. Select 'New Game'
3. Select 'Tuxemon: Spyder and Cathedral'
4. Select any gender
5. Skip intro
6. Put any name
7.  Go through first dialog and select the name of any Tuxemon
8. Go down and right in the first map
9. Talk with shopkeeper
10. Select a Tux on bin
11. Fight the girl
12. After the fight the game freeze.

**Screenshots**
This is where the game become not responsive, there's no dialog and animations (e.g. flowers) and music are still going as normal.
![image](https://github.com/Tuxemon/Tuxemon/assets/30880723/5b1a342a-3c8f-430d-badd-4a38c6553bcd)

**Desktop (please complete the following information):**
 - OS: Debian 12
 - Python Version: 3.11.2

**Additional context**
Inhalation method: Clone the git repo, create a virtual env and run the main python script on main branch.

**Comment by JaskRendix** [comment] 2024-01-31 18:35
I think the issue is inside the variable **battle_last_result**, the player wins/loses and the result gets saved.
Then when it checks for triggering the next dialogue, it doesn't recognize it.

`<property name="cond1" value="is variable_set battle_last_result:won"/>`

**Comment by CourteousCoder** [comment] 2024-02-04 23:34
I'm reviewing #2240 right now. From what I can see, once merged PR #2240 will have resolved issue #2239 [This screenshot](https://i.imgur.com/18l6I1T.png) shows that after winning the first battle, the NPC complains that the newer model is inferior because it lost (expected result).

**Comment by JaskRendix** [comment] 2024-02-05 10:42
@CourteousCoder thanks for double checking

**Comment by HippasusTwo** [comment] 2024-02-15 02:08
@JaskRendix @CourteousCoder 
It's a good change. I tested a battle loss against a wild mon and it gave me a black screen however. Didn't log an error either (beyond 'no rumble backends available' but it always does that).
edit: running away works fine, so does catching.

edit: Okay, I went to a healing center first and then lost a wild battle, and that time it worked.

**Closed as completed** 2024-02-17 23:59 UTC
