### ISSUE TITLE
Collision property to force continuous movement

### ISSUE THREAD

**Issue by MirceaKitsune** [Tuxemon/Tuxemon#264] opened 2017-01-17 02:14 UTC
I initially attempted to code this myself, but the task seems to be beyond my understanding of the Tuxemon code at this date. So for now I decided to post this as an issue, and explain what I wanted to do and why I believe it's needed.

Suggested functionality: Collision entities on maps can already take "from" and "to" parameters, for both "enter" and "exit" directions. For example: If a collision has "enter_from up" and "exit_to down", you can only step on that tile from above and exit it below. The addition I'm suggesting is a "force_to" parameter, which constrains the player to continue walking and doesn't allow them to stop at that tile. If no "exit_to" parameter is set, the player keeps walking forward... if one is set, the player is forced to walk toward the direction specified.

There are mainly two reasons for requesting this: The first are ledges, which are already used on the existing map... you can't climb them (walk upward) but can descend from them (walk downward). The problem is that when you do step down a ledge, you aren't forced to walk all the way across it, and can simply stop in the middle which looks pretty bad (a screenshot of that below). The second reason is that this will allow conveyor belts similar to classic Pokemon games... where if the player steps on a belt tile, they must travel in the direction of the belt until reaching a dead end.

![screenshot_20170117_040316](https://cloud.githubusercontent.com/assets/825418/22005218/13fc852c-dc6a-11e6-8e1d-ebda0e3e9ad3.png)

If anyone attempts this task: The most likely place to implement it seems to be _continue_move in core/components/player.py, where self.tile_destination and self.direction might be forced to a further tile once reaching the initial destination tile.

https://github.com/Tuxemon/Tuxemon/blob/development/tuxemon/core/components/player.py#L862

**Comment by Airon90** [comment] 2017-01-17 18:42
Duplicate of #221

**Comment by MirceaKitsune** [comment] 2017-01-17 19:01
@Airon90 Thanks for mentioning that. Kind of the same thing, though somewhat different still: #221 seems to request actual jumping, which would be better for ledges once it's doable. My suggestion is about chained movement instead... which would also solve the ledge problem in the meantime, but will be needed separately for other things too (such as conveyor belts).

**Comment by MirceaKitsune** [comment] 2017-01-17 22:41
I've actually managed to create a pull request implementing this feature! See #269

**Closed** 2017-01-23 20:45 UTC
