### ISSUE TITLE
Add "bubbles" to the heads of protagonists and NPCS

### ISSUE THREAD

**Issue by DavidLiang1129** [Tuxemon/Tuxemon#1930] opened 2023-06-10 04:30 UTC
**Is your feature request related to a problem? Please describe.**
I think this feature will make certain events more vivid

**Describe the solution you'd like**
I would like Tuxemon to add a feature that displays "bubbles" on the heads of the main characters or NPCS to represent their current emotions, the pictures of the bubbles are here, they use CC0:
https://kenney.nl/assets/emotes-pack
**Describe alternatives you've considered**
We can still use text to indicate the emotions of the main character or NPC, but I don't think it's very vivid (just my personal opinion, if anyone has other ideas, please speak up, thanks!).

**Additional context**
I've seen this design before in Pet Kingdom 3, and I think it would be great for Tuxemon as well

**Comment by JaskRendix** [comment] 2023-06-10 04:42
Duplicate of #667

**Comment by DavidLiang1129** [comment] 2023-06-10 05:03
> Duplicate of #667

Well, look forward to seeing this feature in 0.6!

**Closed as completed** 2023-06-10 05:07 UTC
