### ISSUE TITLE
Game crashed in the grass

### ISSUE THREAD

**Issue by airon90** [Tuxemon/Tuxemon#467] opened 2018-10-07 16:39 UTC
I went to Cotton City and went on the left area. After some steps in the grass, the game crashed. Here is the backtrace:

```
Traceback (most recent call last):
  File "tuxemon.py", line 50, in <module>
    tuxemon.core.main.main(load_slot=args.slot)
  File "/home/airon/Scaricati/Tuxemon-development/tuxemon/core/main.py", line 100, in main
    control.main()
  File "/home/airon/Scaricati/Tuxemon-development/tuxemon/core/control.py", line 568, in main
    update(clock_tick)
  File "/home/airon/Scaricati/Tuxemon-development/tuxemon/core/control.py", line 617, in update
    self.event_engine.update(time_delta)
  File "/home/airon/Scaricati/Tuxemon-development/tuxemon/core/components/event/eventengine.py", line 337, in update
    self.update_running_events(dt)
  File "/home/airon/Scaricati/Tuxemon-development/tuxemon/core/components/event/eventengine.py", line 408, in update_running_events
    action.start()
  File "/home/airon/Scaricati/Tuxemon-development/tuxemon/core/components/event/actions/random_encounter.py", line 92, in start
    current_monster.load_from_db(encounter['monster'])
KeyError: 'monster'
```

**Comment by bitcraft** [comment] 2018-10-08 13:32
Looks like a map error.  @Qiangong2

**Comment by airon90** [comment] 2018-10-08 15:04
Now I'm on mobile. In that map there is also a big bug: I can walk from the upper to a lower part. I'll do a screenshot ASAP

**Comment by airon90** [comment] 2018-10-08 17:09
![schermata da 2018-10-08 18-53-33](https://user-images.githubusercontent.com/139841/46623337-a19a2200-cb2d-11e8-9ff0-1bc2a3216cae.png)
I can go on my left and then go back to the right without being blocked. I can also go down and the up again.
It doesn't always occur but it does.

**Comment by Qiangong2** [comment] 2018-10-08 17:12
Huh, that shouldn't be happening. All the edges are set correctly in Tiled. Seems like sometimes it just glitches and you can walk through

**Comment by Draqolv** [comment] 2018-10-14 07:07
I'm getting the same issue. The problem is in tools.py method load_image. I caught the error down to there. What is happening is that the Filename is empty when it gets passed into here:

```
filename = transform_resource_filename(filename)
return smart_convert(pygame.image.load(filename))
```

I pin pointed this by surrounding random_encounter.py under line 91 with the following:
```
            try:
                current_monster.load_from_db(encounter['monster'])
            except KeyError:
                print "No monster Found in db"
```
Once I did that I was able to get some idea why no monster was getting created for the Monster object. One thing that doesn't make sense is why it wouldn't find a monster key in the encounter dictionary if it was initialized it should have an empty value there, but I haven't delved more into that. I can tell the Filename is empty because I put some debugging info in for load_image inside tools.py below line 143: 
```
    print "tools.py:145 filename: {%s}" % filename
    if filename:
        filename = transform_resource_filename(filename)
        return smart_convert(pygame.image.load(filename))
    raise NameError('Filename is empty')
```
It happens in any of the grass in that map. I haven't tried other maps yet to see what happens in the grass. I'll check and see if those pop up correctly in other maps but I also thought it was interesting that under animate_parties_in method defined on line 347 of combat_animations.py, where we see the filename getting sent to load_sprite, that this is the following snippet:
```
  def animate_parties_in(self):
...
        right_monster = right_trainer.monsters[0]
...
        monster1 = self.load_sprite(right_monster.front_battle_sprite,
                                    bottom=back_island.rect.bottom - scale(12),
                                    centerx=back_island.rect.centerx)
```
That is where the empty filename is coming from. I'm not sure if that is an issue being that there isn't a right_trainer or left because it is a wild tuxemon you enter the combat animation with. The rest look at face value to be defined in a hard coded fashion but this one is calling from right_monster. Don't think that's 100% the problem but that's as far as I got with it thus far.
@Qiangong2 
@airon90
@bitcraft

**Comment by Draqolv** [comment] 2018-10-14 18:50
In Tuxemon\tuxemon\core\components\event\actions\random_encounter.py:89-98 my current code is:
`# Create a monster object
            current_monster = monster.Monster()
            #try:
            from pprint import pprint
            pprint(encounter)
            current_monster.load_from_db(encounter['monster_slug'])
            #except KeyError:
            #    print "No monster Found in db"`
Notice I changed `encounter['monster']` to `encounter['monster_slug']`. I was able to load an encounter while running through the grass in route2.tmx
![image](https://user-images.githubusercontent.com/44131172/46920660-f535c100-cfae-11e8-842d-cb3e9e50459c.png)
This was in random battle 12 and 13 but I suspect all the random battles either have the issue or not. Using my code print I got this message in the terminal while fighting:
```
{u'encounter_rate': 10,
 u'level_range': [3, 6],
 u'monster_slug': u'txmn_aardorn'}
```
That was pretty much all that was spit out but Aardorn loaded seamlessly. What has not loaded thus far is cardiling, bamboon. What has loaded in route1_sanglorian.tmx was axylightl
![image](https://user-images.githubusercontent.com/44131172/46920721-beac7600-cfaf-11e8-8ff0-d40ff12684c5.png)

**Comment by bitcraft** [comment] 2018-10-15 13:50
Wow nice debugging work @Draqolv!  Very cool.  Not all tuxemon are complete, so that is why in your testing cataspike crashed the game.  

@Draqolv @Qiangong2 Just FYI, the route2.json encounters file is not properly formatted (actually, non of them are correct.  only "default_encounters" is good).  I see you didn't commit those files, but that is the problem.  Compare it the the "default_encounter.json" and you will see that they do not match.  `monster_slig` in route2 should be just `monster`.

Cataspike should be removed from the encounters until it is ready to use.

**Comment by bitcraft** [comment] 2018-11-07 14:48
@Draqolv Issue should be fixed now, so I will be closing it.  If it is still an issue, please feel free to reopen.

**Closed by bitcraft** 2018-11-07 14:48 UTC
