### ISSUE TITLE
Can not enter Oak's lab

### ISSUE THREAD

**Issue by HugopGhost** [Tuxemon/Tuxemon#104] opened 2016-03-20 13:03 UTC
The level itself seem to be fine but it crashes when entering.

Terminal: http://pastebin.com/wwzDdUft

**Comment by Nhoya** [comment] 2016-04-09 10:38
```
Same problem here
Traceback (most recent call last):
  File "./tuxemon.py", line 60, in <module>
    main()
  File "/usr/share/tuxemon/core/main.py", line 99, in main
    control.main()
  File "/usr/share/tuxemon/core/control.py", line 512, in main
    self.main_loop()
  File "/usr/share/tuxemon/core/control.py", line 573, in main_loop
    self.update(time_delta)
  File "/usr/share/tuxemon/core/control.py", line 212, in update
    state.draw(self.screen)
  File "/usr/share/tuxemon/core/states/world/worldstate.py", line 232, in draw
    self.fullscreen_animations(surface)
  File "/usr/share/tuxemon/core/states/world/worldstate.py", line 674, in fullscreen_animations
    self.change_map(map_name)
  File "/usr/share/tuxemon/core/states/world/worldstate.py", line 718, in change_map
    map_data = self.load_map(map_name)
  File "/usr/share/tuxemon/core/states/world/worldstate.py", line 754, in load_map
    map_data["data"].loadfile(self.tile_size)
  File "/usr/share/tuxemon/core/components/map.py", line 382, in loadfile
    surface = PygAnimation(images_and_durations)
  File "/usr/share/tuxemon/core/components/pyganim.py", line 108, in __init__
    assert self.numFrames > 0, 'Must contain at least one frame.'
AssertionError: Must contain at least one frame.
```

**Comment by luckymouse0** [comment] 2016-04-21 17:15
Replacing the "tileset" xml tags in "professor_lab.tmx" by the "tileset" from "bedroom_test.tmx", will let you enter the lab.

So my guess is, the tilesets in professor_lab.tmx are wrong...

**Comment by ShadowApex** [comment] 2016-04-22 06:23
This issue has been fixed in the latest commit to the development branch: 1b2c74a88496ae2ab10810ca54e7ba05ebf5062c

This issue was caused by there being tiles with empty "frames" tile properties for some reason. Tuxemon will now correctly handle this case by not trying to create an animation object with no animation frames.

**Closed by ShadowApex** 2016-04-22 06:23 UTC
Labels: bug
