### ISSUE TITLE
Locking controls is not working [untested]

### ISSUE THREAD

**Issue by Qiangong2** [Tuxemon/Tuxemon#790] opened 2020-05-19 01:00 UTC
Normally, after using player_stop, the player cannot move until player_resume has been called. However, the game acts like player_resume has been called if the event sequence ends. This is problematic for long events as it forces them to be overly long/complicated, or split into multiple tiny ones. player_stop should continue to be enforced across events until player_resume is called

**Comment by kerizane** [comment] 2020-05-20 19:01
Can you provide an example?

**Comment by Qiangong2** [comment] 2020-05-20 19:16
> Can you provide an example? 

After you listen to Allie and go to leave, your mom stops you and brings you inside. If you run while the pathfind happens, since that's the last event, pathfind stops and player resume is initiated.

**Comment by bitcraft** [comment] 2020-05-22 14:10
Stop, as it applies to all on screen sprites (players and NPC) is directed at the current movement, nothing to do with controls specifically (only referred to for the player because reseting controls is required....the underlying changes to the sprite are the same for the player sprite and npcs).  Here is the documentation for it:
```python
    def stop_player(self):
        """ Reset controls and stop player movement at once.  Do not lock controls

        Movement is gracefully stopped.  If player was in a movement, then
        complete it before stopping.

        :return:
        """
```
The player resume function is very old and idk if it has worked for a long time (years...).  I can confirm that right now it doesn't do anything.  It should be removed or fixed.

I don't see a problem with stop at the moment.  If you are having issues because the player can move the char. around between events, you should lock the controls....which i guess is not possible.  We need an event for that.

**Comment by bitcraft** [comment] 2020-05-22 14:11
> If you run while the pathfind happens, since that's the last event, pathfind stops 

To go a bit further on, there is only one path for any on-screen sprite.  There is no "stack" that allows us to "go back" to previous movements like a pathfind, or anything else.

**Comment by Sanglorian** [comment] 2020-08-21 01:29
I've corrected the [event reference](https://wiki.tuxemon.org/index.php?title=Event_Reference).

Should we put a request for a way to lock player controls in a separate issue or treat this issue as that request?

**Comment by bitcraft** [comment] 2020-08-28 16:18
I think that the core issue is with ```lock``` and ```unlock```.  I'll update the title to reflect that.

**Comment by Jameskmonger** [comment] 2021-03-01 10:38
I've got a WIP fix for this. Should be completed soon https://github.com/Tuxemon/Tuxemon/pull/840

**Closed** 2022-08-06 20:23 UTC
Labels: Possible Close
