### ISSUE TITLE
combat_started error

### ISSUE THREAD

**Issue by Qiangong2** [Tuxemon/Tuxemon#302] opened 2017-05-12 18:00 UTC
I am trying to make it so that when you talk to an npc before the battle, it only shows once, then the battle starts.

when the condition "not combat_started" is added, you get this error:

**AttributeError: 'WorldState' object has no attribute 'battle_transition_in_progress'**

**Comment by bitcraft** [comment] 2017-05-12 21:01
Could you post the actions and condtions that you are using?

**Comment by Qiangong2** [comment] 2017-05-13 06:39
![capture](https://cloud.githubusercontent.com/assets/16091790/26023220/437fbcb2-376c-11e7-9557-4ef96d1576df.PNG)

**Comment by Qiangong2** [comment] 2017-05-13 06:39
there it is @bitcraft

**Comment by bitcraft** [comment] 2017-05-13 18:50
Qinagong2, I've tested a fix for this problem and it doesn't crash and seems to work.  Please close the issue if your problem is fixed ^_^

**Comment by Qiangong2** [comment] 2017-05-14 00:58
@bitcraft 

It still does not work, even when combat has started. The dialog box will still show up, right after the battle sequence is initiated

**Comment by bitcraft** [comment] 2017-05-14 20:57
I cannot verify this, but it seems that the dialog is opened, then the combat state is started, so technically, it is working as it should.  The issue could be that the combat state starts after the dialog, and therefore gets control.  After the battle, the game return to the dialog.  

It seems that you want to wait for the dialog to close, then start combat.  I don't know if there is a way to wait for a closed dialog.  Maybe @shadowapex knows.

**Comment by Qiangong2** [comment] 2017-05-14 23:34
What I am trying to do is have 2 dialogs. The first appears when you have not battled the npc yet or battled and lost, starting a battle, and the second only shows after you have battled the npc and won.

**Comment by bitcraft** [comment] 2017-05-15 01:30
Ok.  I think that this situation would be solved best with a new condition: won_last_battle.  It will be true if the last battle was won.

You are doing a lot of great work thank you!  You have been using more parts of the maps than there is code for...  Your opinion is important, if there is an action or condition that will help you, or if you want to change something, please tell us.

What do you think about the condition "won_last_battle"?

**Comment by Qiangong2** [comment] 2017-05-15 05:46
No problem, I've had fun working on this :)

If it could be used for a specific npc, that would work. We wouldn't want it to just activate after you battle someone else or a random encounter.

**Comment by bitcraft** [comment] 2017-05-15 10:29
Yeah.  There would have to be some kind of restriction for it to work well.

**Comment by ShadowApex** [comment] 2017-05-15 20:54
> It seems that you want to wait for the dialog to close, then start combat. I don't know if there is a way to wait for a closed dialog. Maybe @ShadowApex knows.

There is an action called [`wait_for_input`](https://github.com/Tuxemon/Tuxemon/wiki/Event-Reference#wait_for_input) which will pause the execution of actions until the given input is received. You could use this to display a dialog, then wait for input, then start combat when the dialog closes.

**Comment by Qiangong2** [comment] 2017-05-15 21:07
@ShadowApex 

I just tried it and the combat music starts as soon as the dialog shows up, but the actual battle does not until the dialog is closed.

**Comment by bitcraft** [comment] 2017-05-16 14:18
What about new actions that queue states on the stack, rather than pushing
them directly?  Maybe a modifier?  In this case you could open a dialog
(top of stack), then queue a battle (directly after the new dialog).

**Comment by ShadowApex** [comment] 2017-05-17 21:14
@Qiangong2    
Would you be able to post your updated actions/conditions? Thanks!

@bitcraft     
That could certainly work. We probably need to figure out a system for queueing actions vs executing actions all at once. In some cases we might want to do something like play a sound and open a dialog at the same time, where in other cases we might want to wait for the sound to finish playing, then open a dialog.

**Comment by bitcraft** [comment] 2017-05-17 21:42
What I mean, is rather than push the new combat state to the top of the stack, queue it after the top...put it in #2 position.  The list below illustrates the how the state stack would look as the actions are executed:

1. [before opening dialog] WorldState
2. [dialog is open] DialogState, WorldState
3. [combat state is queued] DialogState, CombatState, WorldState
4. [dialog closes] CombatState, WorldState

So, you can see, after the dialog closes, the combat would start.  No need to queue up sounds or anything.  Actions could be executed all at once.

There is already the ability to enqueue states like this, linked below.  There might be a drawing artifact because of this, but I don't think it would be a difficult feature to implement.

https://github.com/Tuxemon/Tuxemon/blob/development/tuxemon/core/state.py#L317-L326

**Comment by Qiangong2** [comment] 2017-05-18 05:19
@ShadowApex Here are my conditions
![capture](https://cloud.githubusercontent.com/assets/16091790/26187564/d9cf88d8-3b4e-11e7-8df7-b4fcf5839219.PNG)

**Comment by bitcraft** [comment] 2017-05-18 12:05
It looks like a wait_for_dialog action will be the most straightforward solution.  I'll implement it and we'll see how it works.

**Comment by bitcraft** [comment] 2017-05-19 20:02
@ShadowApex 
@dulsi

I've run into a snag with progress on the "wait_for_dialog" action.  The issue may affect how we think about actions in the game.

The issue is that the "context" system implemented by @dulsi doesn't manipulate the stack in a direct way.  For Dialogs, during the execution of actions (act1, act2, etc...) the dialog is not actually created and placed on the stack until after all the actions are read and processed.

So.  Asking the game to wait for the dialog to close before placing the CombatState on the stack will not work because the Dialog will always be placed after the CombatState (because the 'context' is what adds the dialog, and the context is processed after all actions...see linked code)

https://github.com/Tuxemon/Tuxemon/blob/development/tuxemon/core/components/event/__init__.py#L219-L231


Here are my proposals to get this working:

### Implement more 'contexts'
By moving more of the actions to work with 'contexts', then the actions should behave more predictably.  In this case, all of the combat types actions will have to be reimplemented as 'contexts' so that their states are added to the stack in the same order as the dialog.


### Rethink how contexts work and/or fix dialogs
Maybe adding the context to the stack, as well as contexts will be a good solution.  This would require changes to the dialog, so that new dialog lines/menus, etc can be added after it is instanced.  I realize the context system was implemented because the dialog implementation as-is, doesn't have an interface to add lines, etc after it is instanced.  So, idk.


### Implement so hack to make it work
I'm not above hacks.  Basically, the wait_for_dialog action will halt the engine until a dialog pops up, then it will continue to halt it until the dialog goes away.  It just seems less clean to me, but I don't really see this hack being used often.


To wrap it up:

- The context system changes the order of states as they are pushed onto the stack
- 'wait_for_dialog' is not a straightforward action (as i thought it would be!)


Thoughts?  Other solutions?

**Comment by bitcraft** [comment] 2017-06-21 03:45
@Qiangong2 I have changes on a personal branch that address this issue.  Since you are doing most of the advanced map work these days, I'd love your input and testing on it, before I merge it into Tuxemon.  Please use the "302" branch of my fork to develop and test.  In my basic testing, it seems to work correctly, but I would like your input first.

I've been testing the tuxemart map and the interaction with the professor mostly works as expected.  I've changed the dialog actions to dialog_chain, and it works well.  Let me know what you think.

https://github.com/bitcraft/Tuxemon/tree/302

**Comment by bitcraft** [comment] 2017-06-22 04:33
@Qiangong2 could you point me to a map that test the dialog/start_battle error?  I'd like to make sure that it is handled properly.

**Comment by Qiangong2** [comment] 2017-06-22 05:11
@bitcraft https://github.com/Qiangong2/Tuxemon/blob/development/tuxemon/resources/maps/route1.tmx

Karrianna is the sprite you want. You may have to remove some npcs first though.

**Comment by bitcraft** [comment] 2017-06-22 18:17
@Qiangong2 I've looked at the map, but I don't really want to mess around too much modifying your maps and trying to get it to work.  On my local system, I've created an event that tests dialogs and battles, roughly like this:

dialog "start"
start_battle npc_maple
dialog "end"

the result is as you would expect.  A dialog appears with "start", then after the battle, another dialog appears that says "end".

Its a bit rough, no battle transitions, etc, but it works.  Please consider testing my branch with your code, so I can fix any bugs before merging in.  Thanks!

**Comment by Qiangong2** [comment] 2017-06-23 02:53
The battle doesn't start, it just cycles between the dialogs, it does separate them though, the dialogs don't immediately start right after each other.

**Comment by bitcraft** [comment] 2017-06-23 12:59
Are you using the latest commit?

**Comment by Qiangong2** [comment] 2017-06-25 02:48
I am, the battle still does not start

**Comment by bitcraft** [comment] 2017-06-25 03:17
are there monsters in the party?

**Comment by Qiangong2** [comment] 2017-06-25 03:48
Yes                                                                                                                                                                                                                                                                                                                                        Sent from my BlackBerry 10 smartphone.                                                                                                                                                                                                                From: Leif ThedenSent: Saturday, June 24, 2017 8:17 PMTo: Tuxemon/TuxemonReply To: Tuxemon/TuxemonCc: ZhongQian TiaoGong; MentionSubject: Re: [Tuxemon/Tuxemon] combat_started error (#302)are there monsters in the party?

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/Tuxemon/Tuxemon","title":"Tuxemon/Tuxemon","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/Tuxemon/Tuxemon"}},"updates":{"snippets":[{"icon":"PERSON","message":"@bitcraft in #302: are there monsters in the party?\r\n"}],"action":{"name":"View Issue","url":"https://github.com/Tuxemon/Tuxemon/issues/302#issuecomment-310879506"}}}

**Comment by bitcraft** [comment] 2017-06-25 20:46
OK.  you can test my dev branch now.  I'm moving forward with the commit.  Without a traceback or debug information, I cannot comment why your battles do not start.

https://github.com/bitcraft/Tuxemon/tree/development

**Comment by Qiangong2** [comment] 2017-06-26 05:24
Here is the log @bitcraft 

https://pastebin.com/1QnkLVwL

The game just keeps looping

**Comment by bitcraft** [comment] 2017-06-26 16:18
ok.  seems like there is a logic error somewhere else.  please link the
actions/conditions or the map that is used.

**Comment by Qiangong2** [comment] 2017-06-28 05:36
![capture](https://user-images.githubusercontent.com/16091790/27621931-01666876-5b89-11e7-8aaf-f2bb6b70afe8.PNG)

**Comment by Qiangong2** [comment] 2017-06-28 05:39
There are my conditions for creating the npcs (this is all in the route1.tmx that I linked above, if you would prefer that).

**Comment by bitcraft** [comment] 2017-06-28 16:58
I had a hard time debugging this.  There were a couple problems with your map, and a problem with the translated dialog, which are fixed now.  Your map seems to have a broken event however:

![](https://gyazo.com/96d596d6a6269583500b657298af7e26.png)

1. You dont need the wait for input action.
2. the karrianna_battle variable seems to have too many tests

I was able to get it working be removing act1, cond3, and changing "not" to "is" in cond5.  you may have a different solution, but it did work for me.

You can try the new event debugging screen overlay.  its extremely basic now, but works well enough.  it displays all the running events.  red lines are false, green lines are true.  if all lines are green, then the actions will start.

set "collision_map" to 1 to enable all debugging features.  you will be given some basic items, monsters, collisions will be drawn in red, events drawn in blue, and events will be listed on the screen.

![](https://gyazo.com/40677e293529acbf7b291ef84568d3ac.png)

As you can see, its not perfect, but its a start and can be improved later.
![](https://gyazo.com/e7225c129e61f1ccd8a7b5aec6d11019.png)

**Closed** 2017-06-30 18:56 UTC
Labels: bug
