### ISSUE TITLE
Mint 17: Error in `python': corrupted double-linked list

### ISSUE THREAD

**Issue by nukeop** [Tuxemon/Tuxemon#261] opened 2017-01-03 00:37 UTC
I cloned the repo, installed the dependencies, and started the game.
Immediately after leaving the house the game crashes and I'm left with the following message:

`*** Error in `python': corrupted double-linked list: 0x00007fe0bc002c20 ***`

**Comment by ShadowApex** [comment] 2017-01-04 03:07
> I cloned the repo, installed the dependencies, and started the game.
Immediately after leaving the house the game crashes and I'm left with the following message:
> `*** Error in `python': corrupted double-linked list: 0x00007fe0bc002c20 ***`

Thanks for reporting this. I haven't been able to reproduce this issue, myself. Could you provide a little more information about:
1. What version of python you're using
2. Does the crash happen consistently after leaving the house?
3. Can you post the terminal output before the crash?

Thanks!

**Comment by nukeop** [comment] 2017-01-04 11:38
1. python 2.7.6
2. Yes
3. Full log:

```
$ python tuxemon/tuxemon.py 
/home/men/python-proj/Tuxemon/tuxemon/core/platform/__init__.py:22: SyntaxWarning: name '_pygame' is assigned to before global declaration
  global _pygame
No handlers could be found for logger "core.components.rumble"
libpng warning: iCCP: known incorrect sRGB profile
State was not able to be GC'd <core.states.transition.fade.FadeInTransition object at 0x7f12a83938d0>
State was not able to be GC'd <core.states.splash.SplashState object at 0x7f12a8393750>
State was not able to be GC'd <core.states.transition.fade.FadeOutTransition object at 0x7f12a83938d0>
State was not able to be GC'd <core.states.start.StartState object at 0x7f12a8666550>
State was not able to be GC'd <core.states.transition.fade.FadeInTransition object at 0x7f12a8369fd0>
<MenuItem sprite(in 1 groups)> <rect(0, 0, 203, 29)>
<MenuItem sprite(in 1 groups)> <rect(0, 34, 128, 29)>
<MenuItem sprite(in 1 groups)> <rect(0, 68, 278, 29)>
<MenuItem sprite(in 1 groups)> <rect(0, 102, 178, 29)>
<MenuCursor sprite(in 1 groups)> <rect(-40, -11, 30, 50)>
State was not able to be GC'd <core.states.pc.PCState object at 0x7f12a8393c50>
State was not able to be GC'd <core.states.monster.MonsterMenuState object at 0x7f12a8393c10>
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
*** Error in `python': corrupted double-linked list: 0x00007f129c0014d0 ***
Aborted

```

**Comment by bitcraft** [comment] 2020-01-03 08:08
closing due to ticket age

**Closed by bitcraft** 2020-01-03 08:08 UTC
Labels: bug
