### ISSUE TITLE
ERROR unhandled damage category physical special

### ISSUE THREAD

**Issue by Murmele** [Tuxemon/Tuxemon#1184] opened 2022-05-14 12:13 UTC
```
Traceback (most recent call last):
  File "/app/bin/org.tuxemon.Tuxemon.py", line 55, in <module>
    main.main(load_slot=args.slot)
  File "/app/share/Tuxemon/tuxemon/main.py", line 115, in main
    client.main()
  File "/app/share/Tuxemon/tuxemon/client.py", line 305, in main
    update(clock_tick)
  File "/app/share/Tuxemon/tuxemon/client.py", line 356, in update
    self.update_states(time_delta)
  File "/app/share/Tuxemon/tuxemon/client.py", line 379, in update_states
    self.state_manager.update(time_delta)
  File "/app/share/Tuxemon/tuxemon/state.py", line 426, in update
    state.update(time_delta)
  File "/app/share/Tuxemon/tuxemon/states/combat/combat.py", line 214, in update
    self.update_phase()
  File "/app/share/Tuxemon/tuxemon/states/combat/combat.py", line 512, in update_phase
    self.handle_action_queue()
  File "/app/share/Tuxemon/tuxemon/states/combat/combat.py", line 521, in handle_action_queue
    self.perform_action(*action)
  File "/app/share/Tuxemon/tuxemon/states/combat/combat.py", line 848, in perform_action
    result = technique.use(user, target)
  File "/app/share/Tuxemon/tuxemon/technique.py", line 277, in use
    result = self.damage(user, target)
  File "/app/share/Tuxemon/tuxemon/technique.py", line 399, in damage
    damage, mult = self.calculate_damage(user, target)
  File "/app/share/Tuxemon/tuxemon/technique.py", line 378, in calculate_damage
    return formula.simple_damage_calculate(self, user, target)
  File "/app/share/Tuxemon/tuxemon/formula.py", line 125, in simple_damage_calculate
    raise RuntimeError
```

**Desktop (please complete the following information):**
 - OS: Manjaro Linux
 - Python Version 3.9

**Smartphone (please complete the following information):**
 - Device: Computer
 - OS: Linux

**Additional context**
Commit id: 4c5549fa3fcf48ed527631213f96d941c9376d8c

**Comment by bitcraft** [comment] 2022-05-15 01:13
Duplicate of https://github.com/Tuxemon/Tuxemon/issues/1170

**Closed as completed** 2022-06-06 01:02 UTC
